#!/usr/bin/env bun

const ICONS: Readonly<Record<string, string>> = {
  food: "utensils",
  fuel: "fuel",
  groceries: "shopping-basket",
  home: "house",
  bolt: "zap",
  bag: "shopping-bag",
  plane: "plane",
  play: "clapperboard",
  health: "heart-pulse",
  book: "book-open",
  trend: "trending-up",
  trenddown: "trending-down",
  salary: "banknote",
  swap: "arrow-left-right",
  dots: "ellipsis",
  receipt: "receipt",
  users: "users",
  user: "user-round",
  signout: "log-out",
  key: "key-round",
  target: "target",
  coins: "coins",
  list: "list",
  chart: "chart-column",
  wallet: "wallet",
  plus: "plus",
  bell: "bell",
  search: "search",
  calendar: "calendar",
  camera: "camera",
  image: "image",
  check: "check",
  back: "chevron-left",
  arrow: "chevron-right",
  close: "x",
  backspace: "delete",
  gear: "settings",
  trash: "trash-2",
  pencil: "pencil",
  archive: "archive",
  undo: "undo-2",
  alert: "circle-alert",
};

const inner = async (lucideName: string): Promise<string> => {
  const path = `node_modules/lucide-static/icons/${lucideName}.svg`;
  const file = Bun.file(path);
  if (!(await file.exists())) {
    throw new Error(`lucide has no icon named "${lucideName}"`);
  }

  const svg = await file.text();
  const body = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1);

  return body
    .slice(0, body.lastIndexOf("</svg>"))
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s+/g, " ")
    .trim();
};

const entries: string[] = [];
for (const [name, lucideName] of Object.entries(ICONS)) {
  entries.push(`  ${name}: ${JSON.stringify(await inner(lucideName))},`);
}

const banner = [
  "// Generated by scripts/buildIcons.ts. Do not edit.",
  "// Icons are Lucide (ISC), https://lucide.dev.",
  "",
  "export const ICON_NAMES = [",
  ...Object.keys(ICONS).map((name) => `  ${JSON.stringify(name)},`),
  "] as const;",
  "",
  "export type IconName = (typeof ICON_NAMES)[number];",
  "",
  "export const ICONS: Readonly<Record<IconName, string>> = {",
  ...entries,
  "};",
  "",
].join("\n");

await Bun.write("src/infra/web/views/components/icons.generated.ts", banner);

process.stdout.write(`icons: ${Object.keys(ICONS).length} from lucide\n`);
